### ISSUE TITLE
Double main Qwiic connector

### ISSUE THREAD

**Issue by aburio** [sparkfun/Qwiic_Mux_TCA9548A#2]
Any chance that a new version of the board appear with a double main Qwiic connector ?

The idea is to be able to chain multiple TCA9548A on one I2C bus.

If you need held, I can update the eagle files.

Thank you,
Arthur

**Comment by nseidle** [comment]
What a good idea! If you feel like modifiying the eagle files, a PR would be much appreciated. We'll do a branch and then merge once a new version is released.

**Comment by santaimpersonator** [comment]
@nseidle I updated the board and created a [pull request](https://github.com/sparkfun/Qwiic_Mux_TCA9548A/pull/3).

**Comment by santaimpersonator** [comment]
@nseidle I reviewed the board layout with @oclyke and @AndyEngland521. The pull request should be good now. Feel free to close this issue when you are ready.

**Comment by Burnich** [comment]
Thank you @santaimpersonator ! Working on this issue was on my to do, but you have been faster than me 👍

I reviewed the file on my side and everythings looks good to me.

**Comment by santaimpersonator** [comment]
Product revision is live: https://www.sparkfun.com/products/16784

Closing issue.
